DELETE FROM student WHERE STUDENT.ID in (select distinct MARK.STUDENT_ID from MARK JOIN SUBJECT S on S.ID = MARK.SUBJECT_ID where S.GRADE >= 4);
DELETE FROM student WHERE STUDENT.id IN (SELECT DISTINCT student_id from MARK WHERE mark < 4);
DELETE FROM PAYMENTTYPE WHERE NAME='DAILY';
DELETE FROM MARK where MARK<7;